// most common character names in descending order
export default [
  "Host",
  "Judge",
  "Narrator",
  "Presenter",
  "Co-Host",
  "Additional Voices",
  "Anchor",
  "Panellist",
  "TBD",
  "Announcer",
  "Coach",
  "Various",
  "TBA",
  "Crowd",
  "Reporter",
  "Co-Anchor",
  "Various Characters",
  "Commentator",
  "Correspondent",
  "Team Captain",
  "Audience Member",
  "Cast Member",
  "Field Agent",
  "Reporters",
  "Doctor",
  "Man",
  "Woman",
  "Cashier",
  "Guard",
  "Host & Judge",
  "Ring Announcer",
  "Various Voices",
  "Director",
  "Panelist",
  "Assistant",
  "Műsorvezető", // host/moderator (HU)
  "Programleder", // host/moderator (DE)
  "Pedestrian",
  "Zsűri", // judge (HU)
  "Documentary Narrator",
  "Security Guard",
  "Kid",
  "Girl",
  "Host & Moderator",
  "Studio Panelist",
  "Various Other Characters",
  "TV Announcer",
  "Stage Manager",
  "Audience Members",
]
